# syntax=docker/dockerfile:1

FROM golang:1.22.2-alpine3.19 AS go-builder

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# copy project
COPY . .

# install air for hot reloading
#RUN go install github.com/cosmtrek/air@latest
    
RUN CGO_ENABLED=0 GOOS=linux go build -o go-web-accelerator

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 8080